### ISSUE TITLE
Use fabric's puts() instead of accessing sys.stdout

### ISSUE THREAD

**Issue by ygzgxyz** [devxoul/fabric-verbose#1]
fabric already provides [`puts()`](http://docs.fabfile.org/en/latest/api/core/utils.html?highlight=puts#fabric.utils.puts) to print. Since this is an alias for print and is equivalent to current implementation, but it also supports auto flushing option.

**Comment by devxoul** [comment]
There are two reasons for using `sys.stdout.write` instead of `print` or `puts`:
1. **No line break**
   
   Task name and result message need to be printed in same line.
   
   > ```
   > * Pulling source code...
   > ```
   > 
   > (after a while)
   > 
   > ```
   > * Pulling source code... Done
   > ```
2. **Works with quiet context**
   
   ```
   puts("test 1")
   with quiet():
       puts("test 2")  # not shown
   ```

**Comment by ygzgxyz** [comment]
Okay. It was just a suggestion. I would add that there's 'end' argument for puts() and you can pass non-newline character. And one more thing is that every outputs would be hidden in explicit quiet context I think since quiet() is simply and actually an alias for hide('everything').
