### ISSUE TITLE
Work with fabric.api.execute?

### ISSUE THREAD

**Issue by alexkiousis** [devxoul/fabric-verbose#6]
I know this project hasn't been updated for a long time. 

I was wondering if it was possible to integrate it with the new api function **execute** that was introduced in fabric 1.3.

**Comment by devxoul** [comment]
@alexkiousis, It would work if `execute()` is declared in `fabric.api` but I'm not 100% sure.

**Comment by alexkiousis** [comment]
execute is exposed as a fabric.api function. My understanding is that it doesn't return a return code so verbose can't understand the outcome.

From execute's docstring:

```
   :returns:
        a dictionary mapping host strings to the given task's return value for
        that host's execution run. For example, ``execute(foo, hosts=['a',
        'b'])`` might return ``{'a': None, 'b': 'bar'}`` if ``foo`` returned
        nothing on host `a` but returned ``'bar'`` on host `b`.

        In situations where a task execution fails for a given host but overall
        progress does not abort (such as when :ref:`env.skip_bad_hosts
        <skip-bad-hosts>` is True) the return value for that host will be the
        error object or message.
```
